Merge the bash and zsh scripts into a single file.

diff --git a/bin/aceunit b/bin/aceunit
--- a/bin/aceunit
+++ b/bin/aceunit
@@ -13,25 +13,66 @@ declare -g -A tools
 tool=objdump
 name=fixtures
 
-loadToolPlugins() {
-    for ac in $(readlink -f $(dirname $0)/../share/aceunit)/*.ac ; do
-        source $ac
-    done
-}
+if [ -n "$ZSH_VERSION" ]; then
+    setopt shwordsplit
+
+    PROG=$ZSH_SCRIPT
+
+    loadToolPlugins() {
+        for ac in $(cd "$(dirname "$PROG")" ; pwd -P)/../share/aceunit/*.ac ; do
+            source $ac
+        done
+    }
+
+    isToolSupported() {
+        if typeset -f getSymbols_${tool} >/dev/null ; then
+            return 0
+        else
+            return 1
+        fi
+    }
+
+    supportedTools() {
+        echo ${(k)tools}
+    }
+elif [ -n "$BASH_VERSION" ]; then
+    PROG=$0
+
+    loadToolPlugins() {
+        for ac in $(readlink -f $(dirname $PROG)/../share/aceunit)/*.ac ; do
+            source $ac
+        done
+    }
+
+    isToolSupported() {
+        if [[ $(LC_ALL=C type -t getSymbols_${tool}) == function ]] ; then
+            return 0
+        else
+            return 1
+        fi
+    }
+
+    supportedTools() {
+        echo ${!tools[@]}
+    }
+else
+    echo "$0: error: Unsupported shell for AceUnit."
+    exit 1
+fi
 
 usage() {
-    echo "Usage: $0 [OPTION]... OBJECT_FILE..." 1>&2
+    echo "Usage: $PROG [OPTION]... OBJECT_FILE..." 1>&2
 }
 
 version() {
-    echo "$0 version 1.0"
+    echo "$PROG version 3.0.0"
 }
 
 setTool() {
     if [[ -n "${tools[$1]}" ]] ; then
         tool=$1
     else
-        echo "$0: error: unsupported symbol table tool '$1'" >&2 ; exit 1
+        echo "$PROG: error: unsupported symbol table tool '$1'" >&2 ; exit 1
     fi
 }
 
@@ -54,18 +95,18 @@ Options:
               Example: -s _ to strip a leading underscore from the symbol names.
   -t TOOL     Use TOOL for displaying the symbol table.
               Defaults to objdump.
-              Supported tools: ${!tools[@]}.
+              Supported tools: $(supportedTools).
   -v          Print version information and stop.
 
 Examples:
-  $0 leapyear_test.o >testcases.c
+  $PROG leapyear_test.o >testcases.c
     Scans leapyear_test.o for test functions and generates the test fixtures in testcases.c.
 
-  $0 -t nm -b m68k-amigaos-nm -s _ leapyear_test.o >testcases.c
+  $PROG -t nm -b m68k-amigaos-nm -s _ leapyear_test.o >testcases.c
     Scans leapyear_test.o for test functions and generates the test fixtures in testcase.c.
     Uses nm to get the symbol table, with m68k-amigaos-nm as the binary of nm, and stripping leading underscores from the symbol names.
 
-  $0 -t readelf a.o b.o c.o >testcases.c
+  $PROG -t readelf a.o b.o c.o >testcases.c
     Scans a.o, b.o, and c.o for test functions and generates the test fixtures in testcases.c.
     Uses readelf to get the symbol table.
 END
@@ -77,10 +118,10 @@ getSymbols() {
         echo "$binary: File not found." 1>&2
         exit 2
     fi
-    if [[ $(LC_ALL=C type -t getSymbols_${tool}) == function ]] ; then
+    if isToolSupported ; then
         getSymbols_${tool} $1 $2 $3
     else
-        echo "$0: internal error: Unsupported tool ${tool}" 1>&2 ; exit 2
+        echo "$PROG: internal error: Unsupported tool ${tool}" 1>&2 ; exit 2
     fi
 }
 
@@ -120,7 +161,7 @@ generateFxitureStructures() {
     for file in $fixtures; do
         basename=${file%.o}
         echo
-        echo "const aceunit_func_t testcases_$basename[] = {"
+        echo "const aceunit_func_t testcases_${basename}[] = {"
         for testcase in ${testcases[$basename]}; do echo "    $testcase,"; done
         cat << END
     NULL,
@@ -140,7 +181,7 @@ END
 
 generateFixtureTable() {
     cat <<END
-const AceUnit_Fixture_t *$name[] = {
+const AceUnit_Fixture_t *${name}[] = {
 END
     for file in $fixtures; do
         basename=${file%.o}
